on: [pull_request]

name: Test Pull Request
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18.x, 1.19.x]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - name: Test
        run: make test
      - name: Send code coverage
        uses: codecov/codecov-action@v1
        if: matrix.os == 'ubuntu-latest'
        with:
          fail_ci_if_error: true
