on: [push]

name: Test Push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - uses: actions/checkout@v3
      - name: Test
        run: make test
      - name: Send code coverage
        uses: codecov/codecov-action@v1